# Generated by Django 4.1.4 on 2022-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('cache_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('as_of', models.CharField(max_length=100)),
                ('spaces', models.SmallIntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('rate_description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'space count and rate',
                'verbose_name_plural': 'space counts and rates',
                'unique_together': {('zone', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='LeaseCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('as_of', models.CharField(max_length=100)),
                ('leases', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'lease count',
                'unique_together': {('zone', 'as_of')},
            },
        ),
    ]
